import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ClientLayout from './components/layout-client'
import Carousel from './components/carousel'
import Categories from './categories'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/100px logo.png" />
        <title>Ebiv</title>
      </Head>
        <div className="bg-[url(https://cdn.discordapp.com/attachments/981618787491127306/1088401159821213717/bg.png)] bg-cover">
        <ClientLayout>
        <Carousel/>
        <Categories/>
        </ClientLayout>
        </div>
    </>
  )
}
